version: 2.1

orbs:
  node: circleci/node@5.0.3
  heroku: circleci/heroku@2.0.0

jobs:
  build_and_test: 
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm test
          name: Run test for displaying new text
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  deploy: 
    executor: heroku/default
    steps:
      - attach_workspace:
          at: ~/project
      - heroku/deploy-via-git:
          branch: main
          force: true # force push when pushing to the heroku remote, see: https://devcenter.heroku.com/articles/git
workflows:
  test_my_app:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test # only deploy if the build_and_test job has completed
          filters:
            branches:
              only: main # only deploy when on main

# VS Code Extension Version: 1.2.2
